export const Car = 
[{
id: 1,
image: "./assets/fiat_punto.jpg",
marque : "Fiat",
model : "Punto",
kilométrage : 100000,
année :2009,
carburant : "essance",
puissance_fiscale : [5,"ch"],
couleur_du_véhicule : "noir",
type_de_carrosserie : "compact",
etat_du_véhicule : "bon etat",
boite : "auto",
cylindrée : 1.9,
},
{
    id: 2,
    image: "./assets/fiat_punto.jpg",
    marque : "Fiat",
    model : "Punto",
    kilométrage : 100000,
    année :2009,
    carburant : "essance",
    puissance_fiscale : [5,"ch"],
    couleur_du_véhicule : "noir",
    type_de_carrosserie : "compact",
    etat_du_véhicule : "bon etat",
    boite : "auto",
    cylindrée : 1.9,
    },
    {
    id: 3,
    image: "./assets/fiat_punto.jpg",
    marque : "Fiat",
    model : "Punto",
    kilométrage : 100000,
    année :2009,
    carburant : "essance",
    puissance_fiscale : [5,"ch"],
    couleur_du_véhicule : "noir",
    type_de_carrosserie : "compact",
    etat_du_véhicule : "bon etat",
    boite : "auto",
    cylindrée : 1.9,
    }
]
